export type ReverseMap<T> = T[keyof T]

export enum LogEvents {
  UPDATE_WIDGET = 'UPDATE_WIDGET',
  WIDGET_REFRESH = 'WIDGET_REFRESH',
  UNDEFINED_EVENT = 'UNDEFINED_EVENT',
  FETCHED_CREATIVES = 'FETCHED_CREATIVES',
  FETCHED_REFERRAL_CREATIVES = 'FETCHED_REFERRAL_CREATIVES',
  FETCHED_DEMO_CREATIVES = 'FETCHED_DEMO_CREATIVES',
  AUTO_START = 'AUTO_START',
  MANUAL_START = 'MANUAL_START',
  DEMO_START = 'DEMO_START',
  FETCHING_AD = 'FETCHING_AD',
  CHATBOT_MESSAGE_SENT = 'CHATBOT_MESSAGE_SENT',
  CHATBOT_DISCONNECT = 'CHATBOT_DISCONNECT',
  OBS_SETTINGS = 'OBS_SETTINGS',
  OBS_SETTINGS_DEFAULTS = 'OBS_SETTINGS_DEFAULTS',
  OBS_SETTINGS_CUSTOM = 'OBS_SETTINGS_CUSTOM',
  WIDGET_RELOADED = 'WIDGET_RELOADED',
  SESSION_INIT = 'SESSION_INIT',
  PING_SESSIONS = 'PING_SESSIONS',
  DELETE_SESSION = 'DELETE_SESSION',
}

export type LogEventsType = ReverseMap<typeof LogEvents>
