import { CampaignType } from '@/core/types'

import type {
	IPrerollAdset,
	IPrerollAdsetResponse,
} from './types'

export const responseToData = (response: IPrerollAdsetResponse): IPrerollAdset => {
	return {
		id: response.id,
		format: {
			id: response.format.id,
			title: response.format.title,
			description: response.format.description,
			icon: response.format.icon,
		},
		formatEdit: response.format_edit,
		platform: response.platform,
		campaign: {
			id: response.campaign.id,
			slug: response.campaign.slug,
			type: CampaignType.PREROLL,
			title: response.campaign.title,
			description: response.campaign.description,
			category: {
				...response.campaign.category,
				darkMarket: response.campaign.category.is_dark_market,
			},
			holding: response.campaign.holding,
			advertiser: {
				...response.campaign.advertiser,
				wallet: {
					...response.campaign.advertiser.wallet,
					currency: {
						...response.campaign.advertiser.wallet.currency,
						code: response.campaign.advertiser.wallet.currency.code,
						enTitle: response.campaign.advertiser.wallet.currency.en_title,
						ruTitle: response.campaign.advertiser.wallet.currency.ru_title,
						flag: response.campaign.advertiser.wallet.currency.flag,
						visible: response.campaign.advertiser.wallet.currency.visible,
						ptTitle: response.campaign.advertiser.wallet.currency.pt_title,
						esTitle: response.campaign.advertiser.wallet.currency.es_title,
					},
				},
			},
			start: response.campaign.start,
			end: response.campaign.end,
			published: response.campaign.published,
			visible: response.campaign.visible,
		},
		slug: response.slug,
		title: response.title,
		titleAlternative: response.title_alternative,
		description: response.description,
		start: response.start,
		end: response.end,
		startView: response.start_view,
		endView: response.end_view,
		payableType: response.payable_type,
		currency: {
			...response.currency,
			code: response.currency.code,
			enTitle: response.currency.en_title,
			ruTitle: response.currency.ru_title,
			ptTitle: response.currency.pt_title,
			esTitle: response.currency.es_title,
		},
		bidCap: response.bid_cap,
		impressions: response.impressions,
		bidCpa: response.bid_cpa,
		budget: response.budget,
		targetCpa: response.target_cpa,
		targetCtr: response.target_ctr,
		productUrl: response.product_url,
		mobileProductUrl: response.mobile_product_url,
		pixelClicks: response.pixel_clicks,
		pixelClicksScripts: response.pixel_clicks_scripts,
		attachments: response.attachments,
		targeting: {
			tags: {
				list: response.targeting.tags,
				exclude: response.targeting.exclude_tags,
			},
			countries: {
				list: response.targeting.countries,
				exclude: response.targeting.exclude_countries,
			},
			countriesAuditory: {
				list: response.targeting.countries_auditory,
				exclude: response.targeting.exclude_countries_auditory,
			},
			devicesAuditory: {
				list: response.targeting.devices_auditory,
				exclude: response.targeting.exclude_devices_auditory,
			},
			broadcasterLanguages: {
				list: response.targeting.broadcaster_languages,
				exclude: response.targeting.exclude_languages,
			},
			streamers: {
				exclude: response.targeting.exclude_streamers,
				list: response.targeting.streamers.map(streamer => ({
					id: streamer.id,
					name: streamer.name,
					currency: streamer.currency ?? null,
					agency: streamer.agency ? {
						id: streamer.agency.id,
						title: streamer.agency.title,
						currency: streamer.agency.currency,
						useDarkMarketCpm: streamer.agency.use_dark_market_cpm,
						cpm: streamer.agency.cpm ? {
							internalCpa: streamer.agency.cpm.internal_cpa,
							internalCpc: streamer.agency.cpm.internal_cpc,
							internalCpm: streamer.agency.cpm.internal_cpm,
							externalCpa: streamer.agency.cpm.external_cpa,
							externalCpc: streamer.agency.cpm.external_cpc,
							externalCpm: streamer.agency.cpm.external_cpm,
							darkMarketInternalCpa: streamer.agency.cpm.dark_market_internal_cpa,
							darkMarketInternalCpc: streamer.agency.cpm.dark_market_internal_cpc,
							darkMarketInternalCpm: streamer.agency.cpm.dark_market_internal_cpm,
							darkMarketExternalCpa: streamer.agency.cpm.dark_market_external_cpa,
							darkMarketExternalCpc: streamer.agency.cpm.dark_market_external_cpc,
							darkMarketExternalCpm: streamer.agency.cpm.dark_market_external_cpm,
						} : null,
					} : null,
					cpm: streamer.cpm ? {
						internalCpa: streamer.cpm.internal_cpa,
						internalCpc: streamer.cpm.internal_cpc,
						internalCpm: streamer.cpm.internal_cpm,
						externalCpa: streamer.cpm.external_cpa,
						externalCpc: streamer.cpm.external_cpc,
						externalCpm: streamer.cpm.external_cpm,
						darkMarketInternalCpa: streamer.cpm.dark_market_internal_cpa,
						darkMarketInternalCpc: streamer.cpm.dark_market_internal_cpc,
						darkMarketInternalCpm: streamer.cpm.dark_market_internal_cpm,
						darkMarketExternalCpa: streamer.cpm.dark_market_external_cpa,
						darkMarketExternalCpc: streamer.cpm.dark_market_external_cpc,
						darkMarketExternalCpm: streamer.cpm.dark_market_external_cpm,
					} : null,
				})),
			},
		},
		legalCompliance: {
			erid: {
				media: response.legal_compliance.erid.media,
				text: response.legal_compliance.erid.text,
			},
			marker: {
				media: response.legal_compliance.marker.media,
				text: response.legal_compliance.marker.text,
			},
		},
		published: response.published,
		visible: response.visible,
		videoDescriptionText: response.video_description_text,
	}
}