import moment from 'moment'

import type {
	IUpdateBrandAwarenessAdsetData,
	IUpdateBrandAwarenessAdsetPayload,
} from './types'

export const dataToPayload = (data: IUpdateBrandAwarenessAdsetData): IUpdateBrandAwarenessAdsetPayload => {
	return {
		slug: data.slug,
		title: data.title.default,
		title_alternative: data.title.alternative ?? null,
		description: data.description,
		platform: data.platform,
		format: data.format,
		strategy_payment: data.strategyPayment,
		bid_cap: data.bidCap ?? null,
		impressions: data.impressions ?? null,
		cpa: data.cpa ?? null,
		conversions: data.conversions ?? null,
		cpc: data.cpc ?? null,
		clicks: data.clicks ?? null,
		cpa_daily_limit: data.cpaDailyLimit ? +data.cpaDailyLimit : null,
		cpc_daily_limit: data.cpcDailyLimit ? +data.cpcDailyLimit : null,
		frequency: data.frequency ?? null,
		frequency_count: data.frequencyCount ?? null,
		frequency_period: data.frequencyPeriod ?? null,
		streamer_day_limit: data.streamerDayLimit ?? null,
		gender: data.targeting.gender ?? null,
		age_from: data.targeting.age.from ?? null,
		age_to: data.targeting.age.to ?? null,
		mature: data.targeting.mature,
		tags: data.targeting.tags.list,
		exclude_tags: data.targeting.tags.exclude,
		exclude_countries: data.targeting.countries.exclude,
		countries: data.targeting.countries.list,
		exclude_countries_auditory: data.targeting.countriesAuditory.exclude,
		countries_auditory: data.targeting.countriesAuditory.list,
		exclude_devices_auditory: data.targeting.devicesAuditory.exclude,
		devices_auditory: data.targeting.devicesAuditory.list,
		exclude_languages: data.targeting.broadcasterLanguages.exclude,
		broadcaster_languages: data.targeting.broadcasterLanguages.list,
		time_zone: data.timeZone ?? null,
		target_ctr: data.targetCtr ?? null,
		target_evr: data.targetEvr ?? null,
		agencies: data.targeting.agencies,
		streamers: data.targeting.streamers.list,
		exclude_streamers: data.targeting.streamers.exclude,
		conversions_alert_animation: data.conversionAlert.animation,
		conversions_alert_text: data.conversionAlert.text,
		start: data.dates.start ?? '',
		end: data.dates.end ?? '',
		start_view: data.view?.[0] ? moment(data.view[0]).format('HH:mm:ss') : null,
		end_view: data.view?.[1] ? moment(data.view[1]).format('HH:mm:ss') : null,
		margin: data.margin ?? null,
		agency_commission: data.agencyCommission ?? null,
		cpm_percent: data.cpmPercent ?? null,
	}
}
